name: Déploiement sur GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v4

      - name: Téléchargement de l'artéfact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: demo de la clé secrete 
        run: echo "Je sais utiliser la clé : $MON_SECRET"
        env:
          MON_SECRET: ${{ secrets.SECRET }}

      - name: Déploiement final
        id: deployment
        uses: actions/deploy-pages@v4