name: CI Space Word

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci_space_word:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./space-word

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.x'

      - run: npm install

      - run: npm run lint

      - run: npm run audit || true

      - run: npm run test

      - name: Install Cypress Binary
        run: npx cypress install

      - run: npm run test:e2e